name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: gittools/actions/gitversion/setup@v0.9.6
        with:
          versionSpec: "5.x"
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.6
        with:
          useConfigFile: true
          configFilePath: gitversion.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - version
    permissions:
      contents: write      
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.version.outputs.version }}
          release_name: Release ${{ needs.version.outputs.version }}
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' }}

  build:
    runs-on: ubuntu-latest
    needs:
      - version
      - release
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: ASzc/change-string-case-action@v5
        id: repo
        with:
          string: ${{ github.repository }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ steps.repo.outputs.lowercase }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64/v8, linux/arm/v7, linux/ppc64le
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ steps.repo.outputs.lowercase }}:latest
            ghcr.io/${{ steps.repo.outputs.lowercase }}:${{ needs.version.outputs.version }}

